language: node_js
node_js: --lts

branches:
  only:
    - master

before_install:
  - npm install -g hexo-cli

install:
  - npm i

before_script:
  - git config user.name "yajw"
  - git config user.email "yajw@outlook.com"
  - sed -i'' "s~https://github.com/yajw/yajw.github.io.git~https://${ACCESS_TOKEN}@github.com/yajw/yajw.github.io.git~" blog/_config.yml
script:
  - cd blog
  - hexo g
  - hexo d
