language: node_js
node_js: 
  - 15

env:
  - LIBSASS_EXT=no

branches:
  only:
    - source

before_install:
  - npm install -g hexo-cli
  - npm install -g hexo

before_script:
  - git config user.name "yajw"
  - git config user.email "yajw@outlook.com"
  - sed -i'' "s~https://github.com/yajw/yajw.github.io.git~https://${ACCESS_TOKEN}@github.com/yajw/yajw.github.io.git~" blog/_config.yml
script:
  - cd blog
  - npm i
  - hexo g
  - hexo d
